### ISSUE TITLE
The mod is not stable when using the cloud translation api

### ISSUE THREAD

**Issue by ProfGlobal** [ringosham/TranslateMod#1]
The mod does not work correctly after adding its user key, translates text that does not need to be translated, and replaces all letters with "?", when trying to send a message via y, all characters are replaced with"?". Google cloud translation api

**Comment by ringosham** [comment]
Seems to be a bug within text encoding in the built-in Minecraft libraries.

**Comment by ringosham** [comment]
There is an issue with the built-in libraries used for sending translation requests. They can't decode Google's responses correctly. I have to write this from scratch.
