### ISSUE TITLE
"Google translate has stopped responding"

### ISSUE THREAD

**Issue by SpyrowGr** [ringosham/TranslateMod#16]
every like 5 minutes of using the mod this pops up in my chat and doesnt let me talk in any language
I've tried: removing the mod and re-adding it brand new from the github
Trying to wait it out (yeah that took a while but it fixed after 20 minutes for 5 minutes)

![image](https://user-images.githubusercontent.com/76235801/124403690-50e89f80-dd40-11eb-966c-07139b33a0d2.png)
can someone tell me why or how to fix it? I'm using the Google API key

**Comment by ringosham** [comment]
Are you sure you are using the paid version of Google translate and not the free one?

**Comment by ringosham** [comment]
Also I need more info. Minecraft version?

**Comment by ringosham** [comment]
Close due to inactivity
