### ISSUE TITLE
Request to add DeepL translation api

### ISSUE THREAD

**Issue by PFCraft-box** [ringosham/TranslateMod#4]
api introduction document
https://www.deepl.com/en/docs-api/

**Comment by PFCraft-box** [comment]
I can provide you with an Authentication Key if you want.

**Comment by ringosham** [comment]
Might consider adding to the next release.
DeepL supports very few languages. So the mod will fallback to Google if it doesn't support the language.

**Comment by ringosham** [comment]
Integrating DeepL is a bit more difficult than I thought. The lack of language detection makes this impossible.
As DeepL supports way too little languages, we need something that can detect the language of a string of text.
Neither Google (unless the paid version) nor DeepL can provide a reliable service for this.

**Comment by ringosham** [comment]
If anyone managed to find a free service for detecting languages, please let me know.

**Comment by ZacSharp** [comment]
From Deepl's [api documentation](https://www.deepl.com/docs-api/translating-text/) (shortened and reformatted)
Parameter | Optional | Description
-- | -- | --
source_lang | Optional | Language of the text to be translated. Options currently available:<ul><li>"DE" - German</li><li>"EN" - English</li>...</ul>If this parameter is omitted, the API will attempt to detect the language of the text and translate it.

I guess that means it does support detecting the language

**Comment by ringosham** [comment]
DeepL is a good translation engine, but for chat translation it really needs to support more than 11 languages
Until DeepL can do that, this will not be worked on.
