### ISSUE TITLE
Request more text for wynncraft server

### ISSUE THREAD

**Issue by WangJian566** [ringosham/TranslateMod#7]
I am a Taiwanese player who likes foreigners
I hope I can understand more people's chats
But this MOD only translates NPC’s normal dialogue
There are also players who generally split chat
Cannot be used for the chat of my guild branch
The blue text below belongs to the part that has never been translated
![2021-01-29_10 45 52](https://user-images.githubusercontent.com/65722033/106225579-694c0f80-6220-11eb-8b1e-1f3590c0d492.png)

**Comment by WangJian566** [comment]
The green text will be translated
But it often fails

**Comment by ringosham** [comment]
Add this to your regex list
\[(\d{2}:){2}\d{2}] (\w+) \[\w+] shouts: 
Your group number is 2

In the future, please avoid asking how to get it working in Github (This is for bug reporting and feature request only). Ask via Curseforge instead.
