### ISSUE TITLE
Free translation API interface

### ISSUE THREAD

**Issue by LinHuan7** [ringosham/TranslateMod#8]
Hello, ringosham.
I will introduce some Chinese translation API services, most of which are free to use.

1、 Baidu（http://fanyi-api.baidu.com/product/11）

Unlimited number of words, free use, provide more than 200 languages of high-quality translation services, covering Chinese, English, Japanese, Korean, Russian, Portuguese and other popular languages

2、 Tencent cloud（https://ai.qq.com/console/capability/detail/7）

Unlimited number of words, free use, Unlimited number of translation words, free use, providing 15 languages of quality translation services, covering Chinese, English, Japanese, Korean, French, Spanish, Italian, German, (too long, do not want to type)

**Comment by LinHuan7** [comment]
I used your work a few years ago, when yandex provided free translation. But when I used it today, I found that there was a charge for this device, but I didn't have a payment channel. Please update the author as soon as possible. I can't use both Google and yandex

**Comment by ringosham** [comment]
I'm going to try Baidu as I cannot see Tencent's API without making an account first.
However, due to phone number restrictions I cannot make an account (also privacy concerns).
Expect bugs as I am doing this without testing.

**Comment by LinHuan7** [comment]
Wow, I didn't expect you to reply to me so soon. I have registered the API of Baidu and Tencent, and I can borrow you to test it

**Comment by LinHuan7** [comment]
In addition, I can move your works to the later stage mcbbs.net Well, this is a sharing forum for minecraft players

**Comment by ringosham** [comment]
Thanks! Please send your Baidu API APPID (Can be found [here](https://fanyi-api.baidu.com/api/trans/product/desktop?req=developer)) to h123haas@protonmail.com
You are free to share my work to any site as long as you cite the original source, and not profiting from it.

**Comment by LinHuan7** [comment]
The key has been sent to you

**Comment by LinHuan7** [comment]
Does the author have a chance to produce a Chinese version of the interface

**Comment by LinHuan7** [comment]
Does the author have a chance to produce a Chinese version of the interface

**Comment by ringosham** [comment]
I can make a Chinese localization of it. But this is low priority right now.

**Comment by LinHuan7** [comment]
That's great
