### ISSUE TITLE
Not working please help

### ISSUE THREAD

**Issue by thestormblazer** [ringosham/TranslateMod#9]
1.12 version 
When ever I join the game it says something like google translate has stopped responding pausing translations and then it just doesn't work

**Comment by ringosham** [comment]
Google blocked you because too many translation requests are sent. They will unblock you after a few minutes.
Not really the fault of the mod nor Google as the "free" option is using a reserved API on Google's website.

**Comment by thestormblazer** [comment]
Ok to that that's when I first joined with it before I sent any requests so uhh yeah

Also is there a way this can be "fixed"?

I'm willing to bet this is a dumb question so thank you for bearing with me

**Comment by ringosham** [comment]
Unfortunately there aren't any good free translation providers. Free options usually has limited usage or lack of language support.
I'm currently in the process to add Baidu translation to the mod (Default will still be Google) for players who don't have access to Google. That one is free, but they have a plethora of privacy problems. You'll need to verify your phone to use it.
